<html>
<head>
<style>
</style>
</head>
<body>
    <h3.5><br>Hi Admin,</br>
    <br></br>
    <br>The following complaints has been raised by:</br>
    	<br>Name: ${name},</br>
    	<br>Email: ${email},</br>
    	<br>Contact: ${phoneNumber},</br>
    	<br></br>
    	<br>Title: ${title},</br>
    	<br></br>
    	<br>Complaints/Feedback: ${description},</br>
    	<br></br>
    	<br>Thank you</br>
    	<br>TOQQA App</br></h3.5>
</body>
</html>